# Generated by Django 5.2.1 on 2025-05-16 08:07

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maghalat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('content', django_ckeditor_5.fields.CKEditor5Field()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.category', verbose_name='دسته\u200cبندی')),
            ],
        ),
    ]
