# Generated by Django 5.2.1 on 2025-05-16 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_maghalat'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='دسته\u200cبندی')),
            ],
        ),
        migrations.AlterModelOptions(
            name='maghalat',
            options={'ordering': ['-created_at'], 'verbose_name': 'مقاله', 'verbose_name_plural': 'مقالات'},
        ),
        migrations.AddField(
            model_name='maghalat',
            name='preview_image',
            field=models.ImageField(blank=True, null=True, upload_to='maghalat/previews/', verbose_name='تصویر پیش\u200cنمایش'),
        ),
        migrations.AddField(
            model_name='maghalat',
            name='preview_text',
            field=models.TextField(default=1, verbose_name='خلاصه/پیش\u200cنمایش'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='maghalat',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='اسلاگ مقاله'),
        ),
        migrations.AlterField(
            model_name='maghalat',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='crm.category', verbose_name='دسته\u200cبندی'),
        ),
        migrations.AlterField(
            model_name='maghalat',
            name='title',
            field=models.CharField(max_length=200, verbose_name='عنوان'),
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=512, verbose_name='سؤال')),
                ('answer', models.TextField(verbose_name='پاسخ')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='crm.faqcategory', verbose_name='دسته\u200cبندی')),
            ],
        ),
    ]
