# Generated by Django 5.2.1 on 2025-05-17 06:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_faqcategory_alter_maghalat_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InviteRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30, verbose_name='نام')),
                ('last_name', models.CharField(max_length=30, verbose_name='نام خانوادگی')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل')),
                ('phone', models.CharField(max_length=15, verbose_name='شماره تلفن')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('rejected', 'ریجکت شده'), ('accepted', 'پذیرفته شده')], default='pending', max_length=10, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد شده در')),
                ('inviter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to=settings.AUTH_USER_MODEL, verbose_name='دعوت\u200cکننده')),
            ],
            options={
                'verbose_name': 'درخواست دعوت',
                'verbose_name_plural': 'درخواست\u200cهای دعوت',
                'ordering': ['-created_at'],
            },
        ),
    ]
