# Generated by Django 5.2.1 on 2025-05-17 09:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_inviterequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='نام و نام خانوادگی')),
                ('occupation', models.CharField(blank=True, max_length=100, verbose_name='عنوان شغلی')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='personnel_photos/', verbose_name='عکس پروفایل')),
                ('bio', models.TextField(blank=True, verbose_name='درباره')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='تلفن تماس')),
                ('priority', models.PositiveSmallIntegerField(default=0, help_text='ردیف نمایش: هرچه عدد کمتر باشد، زودتر نمایش داده می\u200cشود.', verbose_name='اولویت نمایش')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد شده در')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='به\u200cروزرسانی شده در')),
            ],
            options={
                'verbose_name': 'پرسنل',
                'verbose_name_plural': 'پرسنل\u200cها',
                'ordering': ['priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceAvaiable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='نام خدمت')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('photo', models.ImageField(upload_to='services/', verbose_name='عکس خدمت')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال است')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='available_services', to='crm.category', verbose_name='دسته\u200cبندی')),
            ],
            options={
                'verbose_name': 'خدمت قابل ارائه',
                'verbose_name_plural': 'خدمات قابل ارائه',
            },
        ),
    ]
