# Generated by Django 5.2.1 on 2025-05-18 09:30

import crm.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_personnel_serviceavaiable'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq',
            options={'verbose_name': ' سوال متداول', 'verbose_name_plural': 'سوالات متداول'},
        ),
        migrations.AlterModelOptions(
            name='faqcategory',
            options={'verbose_name': ' دسته\u200cبندی سوالات متداول', 'verbose_name_plural': 'دسته\u200cبندی\u200cهای سوالات متداول'},
        ),
        migrations.AddField(
            model_name='portfolio',
            name='media_type',
            field=models.CharField(choices=[('image', 'تصویر'), ('video', 'ویدیو')], default=1, max_length=10, verbose_name='نوع رسانه'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='personnel',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='personnel_photos/', validators=[crm.models.validate_personnel_file], verbose_name='عکس پروفایل'),
        ),
    ]
