# Generated by Django 5.2.1 on 2025-05-24 18:20

import crm.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_alter_faq_options_alter_faqcategory_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='commission_rate',
        ),
        migrations.AlterField(
            model_name='serviceavaiable',
            name='photo',
            field=models.ImageField(upload_to='services/', validators=[crm.models.validate_ServiceAvaiable_file], verbose_name='عکس خدمت'),
        ),
    ]
