# Generated by Django 5.1.7 on 2025-06-10 09:36

import crm.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_remove_customuser_commission_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='father_name',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='اسم پدر'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='marriage',
            field=models.CharField(blank=True, choices=[('married', 'متاهل'), ('single', 'مجرد')], max_length=10, null=True, verbose_name='تاهل'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='nahve_ashnaii',
            field=models.CharField(blank=True, max_length=15, verbose_name=' نحوه آشنایی'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='parvande_number',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='شماره پرونده'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone_numbersabet',
            field=models.CharField(blank=True, max_length=15, verbose_name='شماره تلفن ثابت'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone_numbersecond',
            field=models.CharField(blank=True, max_length=15, verbose_name='دوم شماره تلفن'),
        ),
        migrations.CreateModel(
            name='ServiceAvaiabledetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='نام خدمت')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='services/', validators=[crm.models.validate_ServiceAvaiable_file], verbose_name='عکس خدمت')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال است')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='available_services', to='crm.serviceavaiable', verbose_name='زیر دسته')),
            ],
            options={
                'verbose_name': 'خدمت قابل ارائه جزییات',
                'verbose_name_plural': 'خدمات قابل ارائه جزییات',
            },
        ),
    ]
